import { Grievance, WardStats } from "./types";

export const DEMO_GRIEVANCES: Grievance[] = [
  {
    id: "GRV-2024-001",
    date: "2024-01-15",
    citizen: "Ramesh Patel",
    category: "Missed Waste Collection",
    ward: "Ward 12",
    priority: "High",
    department: "Waste Collection",
    status: "In Progress",
    description: "Garbage not collected for 3 consecutive days. Bins overflowing.",
    location: "Sector 4, Main Road",
    aiClassification: "High priority — repeated missed collection affecting public health",
  },
  {
    id: "GRV-2024-002",
    date: "2024-01-15",
    citizen: "Priya Shah",
    category: "Garbage Overflow",
    ward: "Ward 15",
    priority: "Critical",
    department: "Sanitation",
    status: "Assigned",
    description: "Community dustbin overflowing near market. Foul smell affecting residents.",
    location: "Market Area, Block B",
    aiClassification: "Critical — public health risk, requires immediate action",
  },
  {
    id: "GRV-2024-003",
    date: "2024-01-14",
    citizen: "Suresh Kumar",
    category: "Illegal Dumping",
    ward: "Ward 21",
    priority: "High",
    department: "Environment",
    status: "New",
    description: "Construction debris dumped illegally on empty plot near school.",
    location: "Plot 45, Near Primary School",
    aiClassification: "High — illegal dumping near educational institution",
  },
  {
    id: "GRV-2024-004",
    date: "2024-01-14",
    citizen: "Meena Joshi",
    category: "Street Cleaning",
    ward: "Ward 28",
    priority: "Medium",
    department: "Street Cleaning",
    status: "Resolved",
    description: "Main street not cleaned for 2 days. Paper and plastic waste on road.",
    location: "Gandhi Chowk, Ward 28",
    aiClassification: "Medium — routine cleaning missed",
  },
  {
    id: "GRV-2024-005",
    date: "2024-01-13",
    citizen: "Anil Desai",
    category: "Segregation Issue",
    ward: "Ward 12",
    priority: "Low",
    department: "Awareness & Compliance",
    status: "Resolved",
    description: "Neighbors mixing wet and dry waste despite multiple warnings.",
    location: "Residential Complex C, Ward 12",
    aiClassification: "Low — awareness intervention recommended",
  },
  {
    id: "GRV-2024-006",
    date: "2024-01-13",
    citizen: "Kavita Nair",
    category: "Dead Animal Waste",
    ward: "Ward 15",
    priority: "Critical",
    department: "Animal Control & Sanitation",
    status: "Resolved",
    description: "Dead dog lying on roadside for over 24 hours.",
    location: "Street 7, Near Park",
    aiClassification: "Critical — disease risk, immediate removal required",
  },
  {
    id: "GRV-2024-007",
    date: "2024-01-12",
    citizen: "Bhavesh Modi",
    category: "Vehicle Issue",
    ward: "Ward 21",
    priority: "Medium",
    department: "Fleet Management",
    status: "Assigned",
    description: "Garbage collection vehicle making loud noise and leaking waste water.",
    location: "Route 3, Ward 21",
    aiClassification: "Medium — vehicle maintenance required",
  },
  {
    id: "GRV-2024-008",
    date: "2024-01-12",
    citizen: "Sonal Trivedi",
    category: "Recycling Request",
    ward: "Ward 28",
    priority: "Low",
    department: "Recycling",
    status: "In Progress",
    description: "Request for recycling bin installation at apartment complex.",
    location: "Sunrise Apartments, Ward 28",
    aiClassification: "Low — service request for recycling infrastructure",
  },
];

export const DEMO_WARD_STATS: WardStats[] = [
  {
    ward: "Ward 12",
    wasteCollected: 4250,
    segregationCompliance: 72,
    activeComplaints: 8,
    resolvedComplaints: 34,
    missedPickups: 3,
    recyclingRate: 28,
  },
  {
    ward: "Ward 15",
    wasteCollected: 3820,
    segregationCompliance: 58,
    activeComplaints: 12,
    resolvedComplaints: 28,
    missedPickups: 7,
    recyclingRate: 21,
  },
  {
    ward: "Ward 21",
    wasteCollected: 5100,
    segregationCompliance: 84,
    activeComplaints: 5,
    resolvedComplaints: 47,
    missedPickups: 1,
    recyclingRate: 35,
  },
  {
    ward: "Ward 28",
    wasteCollected: 2980,
    segregationCompliance: 67,
    activeComplaints: 9,
    resolvedComplaints: 22,
    missedPickups: 4,
    recyclingRate: 24,
  },
];

export const DEMO_DAILY_COLLECTION = [
  { day: "Mon", ward12: 620, ward15: 545, ward21: 730, ward28: 420 },
  { day: "Tue", ward12: 580, ward15: 510, ward21: 760, ward28: 390 },
  { day: "Wed", ward12: 640, ward15: 590, ward21: 710, ward28: 450 },
  { day: "Thu", ward12: 600, ward15: 520, ward21: 740, ward28: 410 },
  { day: "Fri", ward12: 660, ward15: 570, ward21: 800, ward28: 440 },
  { day: "Sat", ward12: 590, ward15: 540, ward21: 680, ward28: 390 },
  { day: "Sun", ward12: 560, ward15: 545, ward21: 680, ward28: 480 },
];

export const DEMO_SEGREGATION = [
  { ward: "Ward 12", wet: 42, dry: 30, recyclable: 18, mixed: 10 },
  { ward: "Ward 15", wet: 35, dry: 27, recyclable: 14, mixed: 24 },
  { ward: "Ward 21", wet: 45, dry: 33, recyclable: 16, mixed: 6 },
  { ward: "Ward 28", wet: 38, dry: 29, recyclable: 15, mixed: 18 },
];

export const COMPLAINT_CATEGORIES = [
  "Missed Waste Collection",
  "Garbage Overflow",
  "Roadside Dumping",
  "Drainage Waste",
  "Street Cleaning",
  "Recycling Request",
  "Illegal Dumping",
  "Dead Animal Waste",
  "Segregation Issue",
  "Vehicle Issue",
  "Other",
];

export const DEPARTMENT_MAP: Record<string, string> = {
  "Missed Waste Collection": "Waste Collection Department",
  "Garbage Overflow": "Sanitation Department",
  "Roadside Dumping": "Environment Department",
  "Drainage Waste": "Drainage & Sewage Department",
  "Street Cleaning": "Street Cleaning Department",
  "Recycling Request": "Recycling Department",
  "Illegal Dumping": "Environment & Legal Department",
  "Dead Animal Waste": "Animal Control & Sanitation",
  "Segregation Issue": "Awareness & Compliance Department",
  "Vehicle Issue": "Fleet Management Department",
  Other: "General Municipal Services",
};
